# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a125cf5607d6755e0643a26e2397b0e675c3ef26763ad374dce90cdbf3f64a934629fe131948af85bd45709967b4021081bdea602e8e7f6da203f0f0ba917cff

test:
  secret_key_base: 960393547e8c0bbc95003c9c20ae71f275817a507e3b2bb5224206a2047ed8c1b81d1f0164c20e2c2b379eb48c72a8dfd9e06d577d18523890e99db50c003e9b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
